apiVersion: v1
kind: Service
metadata:
  name: docx-processor-service
spec:
  type: NodePort # Dùng NodePort để test local dễ dàng
  selector:
    app: docx-processor
  ports:
    - protocol: TCP
      port: 8000      # Port của Service
      targetPort: 8000 # Port của Container
      nodePort: 30000 # Port bạn sẽ truy cập từ trình duyệt (localhost:30000)